#!/bin/sh

sed -i s/X-Status-Area-Permanent-Item=Clock/#X-Status-Area-Permanent-Item=Clock/g /etc/hildon-desktop/status-menu.plugins

echo "[binaryclock_status_area_plugin.desktop]
X-Desktop-File=/usr/share/applications/hildon-status-menu/binaryclock_status_area_plugin.desktop
X-Status-Menu-Position=22
X-Status-Area-Permanent-Item=Clock
" >> /etc/hildon-desktop/status-menu.plugins

pkill -f /usr/bin/hildon-status-menu