#pragma once

#define CMAKE_BINARY_DIR "@CMAKE_BINARY_DIR@/"
#define HILDON_WIDGET_LIB_DIR "@CMAKE_BINARY_DIR@/"
#define HILDON_WIDGET_DATA_DIR "@HILDON_WIDGET_DATA_DIR@/"
#define PATH_RESOURCES "@PATH_RESOURCES@"